name: Million-App-Base-AutoBuilder
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 给 gradlew 执行权限（关键步骤）
      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK & AAB
        run: ./gradlew assembleRelease bundleRelease
        env:
          KEY_STORE_PASSWORD: admin123
          KEY_PASSWORD: admin123
          ALIAS: my-key-alias

      - name: Upload Finished Files
        uses: actions/upload-artifact@v4
        with:
          name: App-Ready-Files
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/bundle/release/*.aab
